### PR TITLE
Handle linux paths on windows.

### PR DESCRIPTION
**Pull request by dsherret**
For #14. I wouldn't be surprised if someone were depending on the previous behaviour, so this seems like a breaking change in behaviour.

This means it will work the same on linux and windows.

### CODE REVIEW

**Comment by dsherret** [comment]
I need to "unixify" the path before checking if it's absolute. I'll fix that tonight.

**Comment by e-cloud** [comment]
@jonschlinkert  could you have a review?

**Comment by jonschlinkert** [comment]
thanks for the ping, and sorry for the delay. I get heartburn from path issues, especially when they are Windows related, and even more so when they are for Linux on Windows (jk!). 

> so this seems like a breaking change in behaviour.

Is this always desired behavior though? Should we expose an option to `unixify` the path root?

**Comment by dsherret** [comment]
@jonschlinkert I think it would be easiest if people provide that by doing the following:

```ts
toAbsoluteGlob("**/*.txt", { root: path.resolve("/") }));
```

That doesn't require an extra option. What do you think?

Side note: In nodejs it seems that `/` will be the current drive letter. So I can do `fs.readFileSync("/somefile.txt", "utf8")` and it will read the file at `C:\somefile.txt`. I believe the main problem would be if someone provided `/` previously for root and was passing that glob to some other code that was relying on it having a drive letter.

**Pull request closed without merging**
